### ISSUE TITLE
OpenGL.raw.EGL._errors.EGLError

### ISSUE THREAD

**Issue by FinnJob** [ARISE-Initiative/robosuite-benchmark#19]
when I run the command "python scripts/rollout.py --load_dir runs/Door-Panda-OSC-POSE-SEED17/Door_Panda_OSC_POSE_SEED17_2020_09_13_00_26_44_0000--s-0/ --horizon 200 --camera frontview", I only can see 9 episode, and then raise the error "OpenGL.raw.EGL._errors.EGLError: <exception str() failed>". I try to fix it, but I fail. What should I do? Thank you!

**Comment by FinnJob** [comment]
The solution I found is that we need to close the render after using it.
use code `env.close()`.

**Comment by Shuger3** [comment]
> The solution I found is that we need to close the render after using it. use code `env.close()`.

I'm sorry but I don't quite understand your meaning. Could you please provide a more specific description?

**Comment by astrawd** [comment]
> The solution I found is that we need to close the render after using it. use code `env.close()`.

when I use this solution, what is going worng. As follows: Traceback (most recent call last):
  File "/home/astrawd3519/PycharmProjects/mujoco/main.py", line 20, in <module>
    obs, reward, done, info = env.step(action)  # 在环境中执行动作
  File "/home/astrawd3519/anaconda3/envs/robosuite/lib/python3.8/site-packages/robosuite/environments/base.py", line 389, in step
    self.sim.forward()
