### ISSUE TITLE
TypeError: no default __reduce__ due to non-trivial __cinit__

### ISSUE THREAD

**Issue by harishbommakanti** [ARISE-Initiative/robosuite-benchmark#2]
While trying to run an experiment using `python scripts/train.py`, the program runs into an error while trying to save the data. This seems to happen when I specify specific .json files to run too. Attached is the run log.

I'd appreciate any help. Thanks!
[rb_bench_errormessage.txt](https://github.com/ARISE-Initiative/robosuite-benchmark/files/5349143/rb_bench_errormessage.txt)

**Comment by cremebrule** [comment]
Huge thanks for bringing up this issue -- there turned out to a be a small (but important) local change on my machine that wasn't added to this repo. Can you please uninstall the current conda environment (`rb_bench`) and re-install using the updated README?

**Comment by harishbommakanti** [comment]
I removed the environment, started from a clean slate, and I got the error which [https://github.com/ARISE-Initiative/robosuite/issues/111](url) is talking about. I remember that I got this maybe a week ago but the problem went away after [https://github.com/ARISE-Initiative/robosuite/pull/112](url) if I'm remebering correctly, I'm not sure why I'm getting the error again. Maybe the wrong robosuite version in the requirements.txt/the yaml needs to be updated, or its just a problem with my config.

Here's the log message for reference, but it's just talking about the missing `robosuite/controllers/interpolators` module:
[rb_bench_errormessage.txt](https://github.com/ARISE-Initiative/robosuite-benchmark/files/5356792/rb_bench_errormessage.txt)

**Comment by cremebrule** [comment]
Good catch -- yes, this is a robosuite version issue. Can you run `pip install robosuite==1.0.1`?

**Comment by harishbommakanti** [comment]
Yeah that looks like it works. It at least got thorough epoch 0! I'll run a full experiment later today and keep you posted.

**Comment by cremebrule** [comment]
Hi @harishbommakanti , how did the experiments turn out? If everything is working, please close the issue. :)

**Comment by harishbommakanti** [comment]
I left it to train over the weekend and the experiment finished all 2000 epochs! I ran the rollout and that worked too so I don't think I'm seeing any more errors.
