### ISSUE TITLE
Teleoperation Click to toggle the camera failed

### ISSUE THREAD

**Issue by yiigu** [ARISE-Initiative/robosuite-benchmark#5]
The command that I used is
```
python robosuite/robosuite/demos/demo_device_control.py --environment Lift --robots Panda --device keyboard --toggle-camera-on-click
```
When I tried to use click to toggle the camera, it did not work. But the space bar sometimes worked to toggle the camera and sometimes changed the status of the gripper. 

I used mac with touch pad. I was wondering whether the click function is incompatible with the click from touch pad.

**Comment by cremebrule** [comment]
Hi @yiigu ,

Yes, this is expected functionality. It's a bit of a misnomer, since it's a click when using the spacemouse (which is what I used when creating / testing that functionality) vs. a spacebar press when using the keyboard. I can change this to `switch-on-press` to make it more generic.
